# This file has been generated by node2nix 1.11.1. Do not edit!

{pkgs ? import <nixpkgs> {
    inherit system;
  }, system ? builtins.currentSystem, nodejs ? pkgs."nodejs_22"}:

let
  nodeEnv = import ./node-env.nix {
    inherit (pkgs) stdenv lib python2 runCommand writeTextFile writeShellScript;
    inherit pkgs nodejs;
    libtool = if pkgs.stdenv.isDarwin then pkgs.cctools or pkgs.darwin.cctools else null;
  };
  nodePackages = import ./node-packages.nix {
    inherit (pkgs) fetchurl nix-gitignore stdenv lib fetchgit;
    inherit nodeEnv;
  };
in pkgs.stdenv.mkDerivation {
  name = "browsertrix";
  src = ./.;
  buildInputs = [nodejs pkgs.git];
  buildPhase = ''
    ln -s ${nodePackages.nodeDependencies}/lib/node_modules ./node_modules
    export PATH="${nodePackages.nodeDependencies}/bin:$PATH"

    echo ${nodePackages.nodeDependencies}/lib/node_modules

    ${nodePackages.nodeDependencies}/bin/webpack --config webpack.prod.js

    cp -r dist $out/
  '';
}
